name: clean_architecture_lints
environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies:
  collection:
  # we will use analyzer for inspecting Dart files
  analyzer: ^4.6.0
  analyzer_plugin: ^0.11.1
  # custom_lint_builder will give us tools for writing lints
  custom_lint_builder:
    git:
      url: https://github.com/andrzejchm/dart_custom_lint.git
      path: packages/custom_lint_builder
      ref: main


dev_dependencies:
  lint: 1.8.2